### ISSUE TITLE
Can't use colors/formatting on /say or /action

### ISSUE THREAD

**Issue by turt2live** [Chatterbox/Chatterbox#23]
Actual output for configuration defined below:
![image](https://cloud.githubusercontent.com/assets/1190097/7904683/c774ea1e-07c2-11e5-8920-dedee6179565.png)

Relevant configuration section:
```yaml
###############
### FORMATS ###
###############

# These formats have a limited variable scope. These are not passed through the message pipeline; they are only parsed
# by Rythm. This also means that special methods like startJSON are not available.
# The sender variable is guaranteed to be a CommandSender, but nothing more.
# The message variable is guaranteed to be a String.
# Those are the only two variables available.
formats:
  say: "&a[@(sender.getName())] @(message)"
  action: "&c* @(sender.getName()) @(message)"
```
